<a href="https://colab.research.google.com/github/DDricko/Ciencia_de_dados_Ebac/blob/main/Mod04_Tarefa_aula_03_a_05_(base)_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [34]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [35]:
# 1) Seu código aqui
# Cria Tabela com o total de acertos dos alunos em cada materia
df_total_geral = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1)
df_total_geral.columns = ['Matemática', 'Português', 'Geografia', 'Inglês', 'História', 'Física', 'Química']
df_total_geral

    Matemática  Português  Geografia  Inglês  História  Física  Química
0            6          7          7       3         1       8        3
1           19         10          0       0         0      11        8
2           14         16          0       5         7       4        4
3           10          7          3       4         0       0        8
4            7          2          2       7         0       9        3
..         ...        ...        ...     ...       ...     ...      ...
95           6          4          7       1         4       9        3
96           8          1          4       6         1       4        3
97          23          5          0       2         4       1        5
98           0         10          3       1         5      10       11
99          11         15          0       1         6       7        2

[100 rows x 7 columns]

In [36]:

## Cria tabela auxiliar com o total de perguntas para cada materia
qtd_perguntas_dic = {'Matemática': 24, 'Português': 18, 'Geografia': 8, 'Inglês': 8, 'História': 8, 'Física': 12, 'Química': 12}

qtd_perguntas_dic

qtd_perguntas_serie = pd.Series(qtd_perguntas_dic)
qtd_perguntas_serie
#

Matemática    24
Português     18
Geografia      8
Inglês         8
História       8
Física        12
Química       12
dtype: int64

In [37]:
#Calcula a porcentagem de acertos
df_total_geral_porcentagem = (df_total_geral / qtd_perguntas_serie) * 100
df_total_geral_porcentagem.round(2)

    Matemática  Português  Geografia  Inglês  História  Física  Química
0        25.00      38.89       87.5    37.5      12.5   66.67    25.00
1        79.17      55.56        0.0     0.0       0.0   91.67    66.67
2        58.33      88.89        0.0    62.5      87.5   33.33    33.33
3        41.67      38.89       37.5    50.0       0.0    0.00    66.67
4        29.17      11.11       25.0    87.5       0.0   75.00    25.00
..         ...        ...        ...     ...       ...     ...      ...
95       25.00      22.22       87.5    12.5      50.0   75.00    25.00
96       33.33       5.56       50.0    75.0      12.5   33.33    25.00
97       95.83      27.78        0.0    25.0      50.0    8.33    41.67
98        0.00      55.56       37.5    12.5      62.5   83.33    91.67
99       45.83      83.33        0.0    12.5      75.0   58.33    16.67

[100 rows x 7 columns]

In [40]:
# 2) Seu código aqui
# Calcula o valor total de acertos de cada aluno
nota_final_aluno = df_total_geral.sum(axis=1)
nota_final_aluno

0     35
1     48
2     50
3     32
4     30
      ..
95    34
96    27
97    40
98    40
99    42
Length: 100, dtype: int64

In [48]:
# 3) Seu código aqui
# Calcula o percentual geral do aluno
qtd_perguntas = qtd_perguntas_serie.sum()
qtd_perguntas

perc_geral_aluno = (nota_final_aluno / qtd_perguntas) * 100
perc_geral_aluno.round(2)

0     38.89
1     53.33
2     55.56
3     35.56
4     33.33
      ...
95    37.78
96    30.00
97    44.44
98    44.44
99    46.67
Length: 100, dtype: float64

In [57]:
# 4) Seu código aqui
alunos_aprovados = perc_geral_aluno.loc[perc_geral_aluno > 45].count()
alunos_aprovados

np.int64(47)

In [92]:
# Exibindo Dataframe com os resultados obtidos
df_total_geral['Nota_Final'] = nota_final_aluno
df_total_geral['Perc_Geral'] = perc_geral_aluno
df_total_geral['Aprovado'] = perc_geral_aluno > 45
df_total_geral

,Matemática,Português,Geografia,Inglês,História,Física,Química,Nota_Final,Perc_Geral,Aprovado
0,6,7,7,3,1,8,3,35,38.888889,False
1,19,10,0,0,0,11,8,48,53.333333,True
2,14,16,0,5,7,4,4,50,55.555556,True
3,10,7,3,4,0,0,8,32,35.555556,False
4,7,2,2,7,0,9,3,30,33.333333,False
...,...,...,...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3,34,37.777778,False
96,8,1,4,6,1,4,3,27,30.000000,False
97,23,5,0,2,4,1,5,40,44.444444,False
98,0,10,3,1,5,10,11,40,44.444444,False
99,11,15,0,1,6,7,2,42,46.666667,True

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [69]:
# seu código aqui
# Cria Dataframe com os alunos desqualificados pelo criterio informado
reprovados = df_total_geral.loc[(df_total_geral['Matemática'] == 0) | (df_total_geral['Física'] == 0) | (df_total_geral['Química'] == 0)]
alunos_reprovados = pd.DataFrame(reprovados)
alunos_reprovados

,Matemática,Português,Geografia,Inglês,História,Física,Química,Nota_Final,Perc_Geral,Aprovado
3,10,7,3,4,0,0,8,32,35.555556,False
6,6,0,7,7,5,0,4,29,32.222222,False
10,10,8,3,2,1,7,0,31,34.444444,False
12,20,8,3,7,1,0,3,42,46.666667,True
14,7,11,1,7,1,4,0,31,34.444444,False
20,23,11,6,5,6,2,0,53,58.888889,True
25,0,4,7,4,0,4,8,27,30.000000,False
26,11,14,6,2,7,0,0,40,44.444444,False
27,21,13,1,5,7,3,0,50,55.555556,True
33,14,8,0,5,6,6,0,39,43.333333,False
35,11,14,6,3,3,0,11,48,53.333333,True
49,8,1,1,0,1,0,8,19,21.111111,False
56,7,6,7,5,6,0,8,39,43.333333,False
65,1,8,2,4,3,0,6,24,26.666667,False
66,5,4,3,6,3,0,10,31,34.444444,False
72,11,16,3,4,7,0,9,50,55.555556,True
73,1,16,2,4,3,0,11,37,41.111111,False
74,9,11,0,7,5,7,0,39,43.333333,False
84,15,1,0,5,1,0,4,26,28.888889,False
89,23,11,7,7,6,9,0,63,70.000000,True
92,14,10,1,6,1,8,0,40,44.444444,False
94,0,5,2,6,1,3,8,25,27.777778,False
98,0,10,3,1,5,10,11,40,44.444444,False

In [71]:
# Contagem de alunos reprovados pelo mesmo criterio
alunos_reprovados.shape[0]

23

In [74]:
# Media desses alunos em historia e geografia
alunos_reprovados[['História', 'Geografia']].mean().round(2)

História     3.43
Geografia    3.22
dtype: float64

In [77]:
# Cria Dataframe com os alunos aprovados
aprovados = df_total_geral.loc[(df_total_geral['Matemática'] > 0) & (df_total_geral['Física'] > 0) & (df_total_geral['Química'] > 0) & (df_total_geral['Aprovado'] == True)]
aprovados_df = pd.DataFrame(aprovados)
aprovados_df

,Matemática,Português,Geografia,Inglês,História,Física,Química,Nota_Final,Perc_Geral,Aprovado
1,19,10,0,0,0,11,8,48,53.333333,True
2,14,16,0,5,7,4,4,50,55.555556,True
5,20,2,5,3,2,9,9,50,55.555556,True
7,18,4,4,7,7,1,8,49,54.444444,True
8,22,9,2,7,6,5,7,58,64.444444,True
11,23,6,2,0,6,4,2,43,47.777778,True
17,21,15,2,2,4,2,6,52,57.777778,True
18,20,4,3,5,3,11,4,50,55.555556,True
24,20,2,7,5,3,11,2,50,55.555556,True
29,16,0,0,2,7,11,8,44,48.888889,True
31,15,13,3,1,3,9,10,54,60.000000,True
34,18,14,1,0,6,3,3,45,50.000000,True
36,22,9,6,6,1,4,8,56,62.222222,True
37,19,12,5,7,1,6,2,52,57.777778,True
39,4,16,2,4,6,9,8,49,54.444444,True
40,18,3,6,3,6,5,6,47,52.222222,True
42,20,6,7,7,2,3,3,48,53.333333,True
44,6,14,7,3,1,3,9,43,47.777778,True
45,17,10,0,2,6,9,4,48,53.333333,True
48,17,6,0,7,5,9,11,55,61.111111,True
50,20,9,0,3,1,7,3,43,47.777778,True
51,1,12,7,3,5,4,10,42,46.666667,True
52,19,5,5,5,0,3,4,41,45.555556,True
53,14,11,3,4,3,7,3,45,50.000000,True
55,11,10,4,4,5,1,6,41,45.555556,True
60,16,8,0,4,4,7,9,48,53.333333,True
62,17,6,2,4,7,1,9,46,51.111111,True
67,21,0,7,2,4,2,10,46,51.111111,True
68,9,9,5,3,6,10,1,43,47.777778,True
70,21,14,0,3,5,11,8,62,68.888889,True
71,17,8,7,6,4,2,9,53,58.888889,True
75,3,6,7,6,6,9,5,42,46.666667,True
77,15,2,5,7,6,11,7,53,58.888889,True
78,14,16,7,2,7,11,9,66,73.333333,True
80,13,16,5,1,7,2,1,45,50.000000,True
81,22,16,2,0,4,1,10,55,61.111111,True
82,7,16,7,1,1,2,9,43,47.777778,True
83,20,1,5,6,3,6,1,42,46.666667,True
88,20,1,1,5,7,9,7,50,55.555556,True
93,12,16,5,5,6,6,6,56,62.222222,True
99,11,15,0,1,6,7,2,42,46.666667,True

In [78]:
aprovados_df.shape[0]

41

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [ ]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-5ed92752-6121-474f-ab37-816918134afc.c000.csv'

In [ ]:
# 1) Sua solução aqui

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 3) solução alternativa

In [ ]:
# 4)

In [ ]:
# 5)

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [ ]:
# 1)

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 4)

In [ ]:
# 5)